// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWmBAIFhs718DtHCitpXjG_ajDdvUHyLA',
    appId: '1:969147271546:web:084376597a3c39f6be2ec3',
    messagingSenderId: '969147271546',
    projectId: 'fir-course-c6321',
    authDomain: 'fir-course-c6321.firebaseapp.com',
    storageBucket: 'fir-course-c6321.firebasestorage.app',
    measurementId: 'G-8VW76VCLKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBD2uysrTOCCmnLmabNZpbf8qvFBhL1BM',
    appId: '1:969147271546:android:4ff384be4468fd92be2ec3',
    messagingSenderId: '969147271546',
    projectId: 'fir-course-c6321',
    storageBucket: 'fir-course-c6321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8rZ33S7LFWNsW6j0DzlFhqkfs3Jd8wCA',
    appId: '1:969147271546:ios:e577d8d7f75fabd6be2ec3',
    messagingSenderId: '969147271546',
    projectId: 'fir-course-c6321',
    storageBucket: 'fir-course-c6321.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8rZ33S7LFWNsW6j0DzlFhqkfs3Jd8wCA',
    appId: '1:969147271546:ios:e577d8d7f75fabd6be2ec3',
    messagingSenderId: '969147271546',
    projectId: 'fir-course-c6321',
    storageBucket: 'fir-course-c6321.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWmBAIFhs718DtHCitpXjG_ajDdvUHyLA',
    appId: '1:969147271546:web:e36c67f1ec602125be2ec3',
    messagingSenderId: '969147271546',
    projectId: 'fir-course-c6321',
    authDomain: 'fir-course-c6321.firebaseapp.com',
    storageBucket: 'fir-course-c6321.firebasestorage.app',
    measurementId: 'G-V058ZB39QV',
  );
}
